### ISSUE TITLE
gaffer qiut working

### ISSUE THREAD

**Issue by rickcreations** [gregzaal/Gaffer#107]
I love the gaffer addon, but for some reason its no longer in the world tab or any other place. its still in preferences, but when you check it to enable it there's an error accurs. 
Thank you for any help you can provide
Thank you Rick
![Screenshot (6)](https://user-images.githubusercontent.com/50303381/57559592-e4301100-733f-11e9-87e1-d82787aa1c7e.png)

**Comment by rickcreations** [comment]
![Screenshot (28)](https://user-images.githubusercontent.com/50303381/57559709-6d474800-7340-11e9-873c-74e7c89482df.png)
Sorry wrong one

**Comment by gregzaal** [comment]
That error says there was an error loading the `_socket` module, so it seems most likely that it's an issue with using the wrong version of Blender.

**Comment by rickcreations** [comment]
I checked the addon is for blender 2.79 and that the version I'm using.  I did save some blend files from a 32 bit computer from the blender class I teach here at a Art center. By opening 32 bit files on a 64 bit computer can that cause a loading error.  It seems the gaffer addon was working good just until a couple of days a go when I started loading file from my work computer.  I'll try to find any 32 bit files and delete them maybe that will correct the problem. If that doesn't work I'll reload blender and try to 
reinstall the addon.  If you have any ideas please let me know.
thank you

**Comment by gregzaal** [comment]
That does sound suspicious. The `_socket` module is built into blender since quite a while ago, so if it's having trouble importing that module then there's something pretty broken low level that doesn't have anything directly to do with Gaffer.

You can try downloading and installing blender again, or using a more recent 2.79 build from builder.blender.org.

Closing this as there's nothing I can do about it, it's not something I can fix in Gaffer but something broken in your system.
