### ISSUE TITLE
FR: Scrollbars in preview popup

### ISSUE THREAD

**Issue by foreachthing** [gregzaal/Gaffer#121]
Without scrollbars, it's much easier to use the standard "file open" dialog.
I got some +400 hdri's and it's become very difficult to browse through all of them. But I don't want to miss out on the features like brightness, rotation etc.

Additional, possibly useful, FRs:
* make thumbnails smaller, larger, list (names only)

I'm on Blender 2.90

**Comment by gregzaal** [comment]
The main purpose of the thumbnail popup is to get around the incredibly slow thumbnail loading in blender's file browser (in some cases the thumbnails images in the file browser don't even load at all), because it has to read the HDR file itself and generate its own thumbnail.

With Gaffer, the thumbnails are pre-generated and just need to be read from disk, but this can still be slow if you have a lot because it reads them in alphabetical order (from the top), while the preview popup is by default scrolled to the bottom, and the lack of a scrollbar is quite annoying.

This preview popup thing that lacks scrollbars is built into blender itself and there's no way to improve upon it (from an add-on) without recreating a whole new popup element, which would be quite a considerable amount of work. But I agree it should be done at some point anyway.

The best way around this limitation is to use the search bar and filter your HDRIs down so there's less to scroll through. All the HDRI Haven HDRIs automatically come with tags you can search for (like "outdoor", "indoor", "high contrast", etc), otherwise you need to add your own tags to each HDRI to help you find them in future.

> make thumbnails smaller, larger
This is a matter of preference and display size, so it could be made into an option.

> list (names only)
Do you really know all 400 of your HDRIs by name? I feel like a thumbnail preview is a hugely important part of being able to find the kind of HDRI you want.

**Comment by AlexFundorin** [comment]
Is it possible to add an option for scrolling thumbnails in a reverse direction? I guess that you're using macOS, but it's counter intuitive when scrolling on windows.
I would also like to see the folder structure in the thumbnails popup. Scrolling through hundreds of HDRI's could be a very tedious task. Thanks in advance.

P.S. Having an option to resize thumbnails would be nice.

**Comment by gregzaal** [comment]
This may be solved by #131 - if not, I don't think it's reasonable to rewrite a huge chunk of Blender's UI code just to have scrollbars.
