### ISSUE TITLE
Save the directory of HDRI specified by the user

### ISSUE THREAD

**Issue by blenderskool** [gregzaal/Gaffer#31]
It would be really handy if the directory of the hdri specified by the user remains there till the user changes it next time.

Essentially save the path so that it is setup automatically next time

**Comment by gregzaal** [comment]
It's just a normal User Preference, so it is saved when the user clicks "Save User Settings" at the bottom left. I don't think it's wise to automatically save the user preferences since they may have changed something else temporarily.

It could be saved to a separate file (the settings.json) instead of being a user preference, that would be more permanent, but I'm not sure what disadvantages that might have.

**Comment by blenderskool** [comment]
Yeah, I am adding a system to save it as another file,
It is not good to save Users settings 😄

**Comment by gregzaal** [comment]
Note that there is a bit of a system in place for this sort of thing already - see the get_persistent_setting and set_persistent_setting functions in functions.py

**Comment by blenderskool** [comment]
Yep, I have used that and added this
