### ISSUE TITLE
error creating thumbnail

### ISSUE THREAD

**Issue by LukeDice** [gregzaal/Gaffer#67]
when i create thumbanil it doeesnt work.

![error thumb](https://cloud.githubusercontent.com/assets/25964923/23230644/0e5be840-f945-11e6-9be0-b1a8a21dccee.jpg)

**Comment by gregzaal** [comment]
That's odd. Looks like blender is some how reading the image file with a width of 0. Is there anything unusual about that `._Annecy` file?

**Comment by LukeDice** [comment]
deleting ._Annency file thumbs are created.   Some thumbs appears broken like in the photo below


![error2](https://cloud.githubusercontent.com/assets/25964923/23231776/513e45b4-f949-11e6-94f8-da5516db5cb1.jpg)

**Comment by gregzaal** [comment]
@LukeDice I think I've fixed your issues, can you test it?

1. Remove Gaffer from the User Preferences
2. Download and install [this Zip](https://github.com/gregzaal/Gaffer/archive/master.zip)

If you have trouble installing it again, locate the folder where Blender add-ons are stored on your system (typically `C:\Users\yourname\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons`) and make sure the Gaffer folder is named `Gaffer` and not `Gaffer-master` or something else.

If you still have the same problem, please send me the files that do not work so that I can test with them.
